name: Java CI with Gradle
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: server
        path: build/libs/*.jar
        retention-days: 5
  
 heroku:
  needs: build
  runs-on: ubuntu-latest
  
  steps:
  
  - name: Download a single artifact
    uses: actions/download-artifact@v2
    with:
      name: server
      
  - name: Login to Heroku Container registry
    uses: docker/login-action@v1
    with:
      registry: registry.heroku.com
      Username: f.matorin@mail.ru
      Password: ${{ secrets.HEROKU_API_KEY }}
    
  - name: Build and push docker container
    uses: docker/build-push-action@v2
    with:
      context: ${{ env.DOCKER_CONTEXT }}
      push: true
      tags: ${{ env.GITHUB_SHA_SHORT }}:${{ env.GITHUB_REF_SLUG }}
