name: Push
on:
  push:
    branches: [ master ]

jobs:

 heroku:
   runs-on: ubuntu-latest
   env:
     DOCKER_REGISTRY: registry.heroku.com
     MAIN_DOCKER_IMAGE_NAME: license-diplom
  
   steps:
  
   - name: Checkout repo
     uses: actions/checkout@v1
   
   - name: Inject slug/short variables
     uses: rlespinasse/github-slug-action@v3.x
  
   - name: Download a single artifact
     uses: actions/download-artifact@v2
     with:
       name: server
      
   - name: Login to Heroku Container registry
     uses: docker/login-action@v1
     with:
       registry: registry.heroku.com
       Username: f.matorin@mail.ru
       Password: ${{ secrets.HEROKU_API_KEY }}
    
   - name: Build and push docker container
     uses: docker/build-push-action@v2
     with:
       context: .
       push: true
       tags: registry.heroku.com/license-diplom/web

   - name: Release
     env:
       HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
       run: heroku container:push ${{ secrets.HEROKU_APP_NAME }} web
     run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web
